Fix multiline log when starting osiris_replica_reader
rabbitmq/osiris pull request #59
Opened 2021-10-20 08:38 UTC by lhoguin

A user on Slack reported this one taking a lot of lines: https://rabbitmq.slack.com/archives/C1EDN83PA/p1634681329322400

I have not tested it.

2021-10-20 08:40 UTC, michaelklishin approved these changes

2021-10-20 08:54 UTC, lhoguin commented
I don't understand why the test end in failure, the artifacts that I download say everything was successful, but the GHA output says 1 failed?

2021-10-21 07:57 UTC, pjk25 commented
@lhoguin actions for this project currently execute the tests both with Erlang.mk and with Bazel. From what I see, the checks under bazel are green, but under Make/Erlang.mk, they are not. The last line is

```
make: *** [erlang.mk:6495: ct] Error 1
```

Line 6495 in `erlang.mk` is

```
	$(gen_verbose) $(CT_RUN) -sname ct_$(PROJECT) -suite $(addsuffix _SUITE,$(CT_SUITES)) $(CT_OPTS)
```

So it seem that `ct_run` is not returning 0? Bazel is ultimately using `ct_run` as well, so it's not clear to me where the discrepancy arises.

2021-11-01 09:01 UTC, kjnilsson requested changes
I think we can either make this log DEBUG or remove the logging of the args completely. Or both. Putting them all on one line doesn't make a lot of sense to me as that is a logger configuration issue.

2021-11-03 10:41 UTC, lhoguin commented
@kjnilsson Up to you, I don't know what the log is about.

This is the default RabbitMQ logger configuration for what it's worth. Personally I don't think anything should ever be logged multiline (outside the most common debug output), because it's trivial to reformat as multiline when necessary.

2022-03-20 20:24 UTC, closed without merging